Feature/TR-765/load test taker response in audio PCI
oat-sa/extension-tao-outcomeui pull request #374
Opened 2021-03-18 15:36 UTC by jsconan

Related to: https://oat-sa.atlassian.net/browse/TR-775

Requires: 
 - [ ] https://github.com/oat-sa/tao-item-runner-qti-fe/pull/159
 - [ ] https://github.com/oat-sa/extension-tao-itemqti/pull/1662
 - [ ] https://github.com/oat-sa/extension-tao-itemqti-pci/pull/221

Update the Results page to allow loading the file content related to QTI file variables. This mainly aims the `audioRecording` PCI, but technically it could apply to any interaction working with a file variable.

Basically, here is what changed:
- the Results controller gets an additional endpoint to serve the file content from a QTI variable
- the variable formatted is supplying the variable URI  instead of replacing the file variable by an empty value
- the `viewResults` client controller scrutinizes the response state of the item, searching for partial file response, then it loads the file content thanks to the supplied variable URI and updates the state before opening up the review component

How to test:
- apply the companion PRs
- take a test containing an audio PCI (you may use the one linked in the ticket)
- login in the backoffice and go to the results page
- review the item containing the audio PCI, it should allow to replay the record

**Note:** for the being, a regression exists because of RE-228. This prevent the state to be available for the item review. While the fix is not there, you can workaround this issue by applying this patch:
- open `taoOutcomeUi/model/ResultsService.php`
- replace the line 608 by `$variablesByItem[$time] = array_merge($variablesByItem[$time]??[], $this->getItemInfos($itemCallId, [[$itemVariable]]));`

2021-03-19 14:07 UTC, btamas reviewed
I have this error on result page. Is it related?
<img width="674" alt="Screen Shot 2021-03-19 at 15 06 19" src="https://user-images.githubusercontent.com/537151/111792674-c1b89880-88c4-11eb-8963-6e959a59bcef.png">

2021-03-19 14:09 UTC, btamas requested changes

2021-03-19 14:09 UTC, btamas commented on views/js/controller/viewResult.js
> +                        console.log(JSON.stringify(state));
Console.log

2021-03-19 14:09 UTC, btamas commented on views/js/controller/viewResult.js
> +                        console.log(JSON.stringify(state));
one more

2021-03-19 14:58 UTC, jsconan commented
> I have this error on result page. Is it related?
> <img alt="Screen Shot 2021-03-19 at 15 06 19" width="674" src="https://user-images.githubusercontent.com/537151/111792674-c1b89880-88c4-11eb-8963-6e959a59bcef.png">

Yes, this is related to RE-228, as mentioned in the PR description. I'll check if a fix has been put on develop and I'll merge it

2021-03-19 15:01 UTC, jsconan commented on views/js/controller/viewResult.js
> +                        console.log(JSON.stringify(state));
oh lord! My bad. Fixed

2021-03-19 15:04 UTC, jsconan commented
The PHP issue should be fixed now. I merged back develop.

2021-03-19 15:31 UTC, btamas commented
> Yes, this is related to RE-228, as mentioned in the PR description. I'll check if a fix has been put on develop and I'll merge it

I've not read that part.

2021-03-19 15:53 UTC, btamas approved these changes
Works fine, but I was not able to check PHP.

- [ ] New code is covered by tests (if applicable)
- [ ] Tests are running successfully (old and new ones) on my local machine (if applicable)
- [ ] New code is respecting code style rules
- [ ] New code is respecting best practices
- [ ] New code is not subject to concurrency issues (if applicable)
- [ ] The feature is working correctly on my local machine (if applicable)
- [ ] Acceptance criteria are respected
- [x] Pull request title and description are meaningful
- [x] Pull request's target is not `master`

2021-03-22 07:58 UTC, augustas approved these changes
- [ ] New code is covered by tests (if applicable)
- [x] Tests are running successfully (old and new ones) on my local machine (if applicable)
- [x] New code is respecting code style rules
- [x] New code is respecting best practices
- [ ] New code is not subject to concurrency issues (if applicable)
- [x] Feature is working correctly on my local machine (if applicable)
- [x] Acceptance criteria are respected
- [x] Pull request title and description are meaningful

2021-03-22 07:59 UTC, tikhanovichA approved these changes
**Review Checklist**
- [ ] New code is covered by tests (if applicable)
- [ ] Tests are running successfully (old and new ones) on my local machine (if applicable)
- [x] New code is respecting code style rules
- [x] New code is respecting best practices
- [ ] New code is not subject to concurrency issues (if applicable)
- [x] The feature is working correctly on my local machine (if applicable)
- [x] Acceptance criteria are respected
- [x] Pull request title and description are meaningful

2021-03-22 08:53 UTC, anshul119 approved these changes
Works as expected! 

**Review Checklist**
- [ ] New code is covered by tests (if applicable)
- [x] Tests are running successfully (old and new ones) on my local machine (if applicable)
- [x] New code is respecting code style rules
- [x] New code is respecting best practices
- [ ] New code is not subject to concurrency issues (if applicable)
- [x] The feature is working correctly on my local machine (if applicable)
- [x] Acceptance criteria are respected
- [x] Pull request title and description are meaningful

2021-03-22 09:26 UTC, merged