fix: left building columns only in worker task runtime
oat-sa/extension-tao-outcomeui pull request #454
Opened 2022-12-20 14:16 UTC by pnal

2022-12-23 08:17 UTC, Karol-Stelmaczonek approved these changes
- [ ] New code is covered by tests (if applicable)
- [ ] Tests are running successfully (old and new ones) on my local machine (if applicable)
- [ ] New code is respecting code style rules
- [x] New code is respecting best practices
- [x] New code is not subject to concurrency issues (if applicable)
- [ ] Feature is working correctly on my local machine (if applicable)
- [x] Acceptance criteria are respected
- [x] Pull request title and description are meaningful

2022-12-23 08:17 UTC, Karol-Stelmaczonek commented on model/export/SingleDeliveryResultsExporter.php
>      public function setColumnsToExport($columnsToExport)
suggestion: you removed is_string check then probably you can define array type for $columnsToExport

2022-12-29 10:12 UTC, bartlomiejmarszal requested changes
[**Review Checklist**
- [ ] New code is covered by tests (if applicable)
- [x] Tests are running successfully (old and new ones) on my local machine (if applicable)
- [x] New code is respecting code style rules
- [x] New code is respecting best practices
- [ ] New code is not subject to concurrency issues (if applicable)
- [ ] Feature is working correctly on my local machine (if applicable)
- [x] Acceptance criteria are respected
- [x] Pull request title and description are meaningful
- [ ] Pull request's target is not `master`
- [ ] Commits are following [conventional commits](https://www.conventionalcommits.org/en/v1.0.0/)
- [ ] Commits messages are meaningful
- [ ] Commits are atomic
- [ ] Changelog is updated according to changes (if applicable)
- [ ] Documentation is updated according to changes (if applicable)

2022-12-29 10:12 UTC, bartlomiejmarszal commented on scripts/task/ExportDeliveryResults.php
> +                                [
extract this to method

2022-12-29 12:55 UTC, pnal commented on model/export/SingleDeliveryResultsExporter.php
> +    private function saveToLocal(AbstractFileExporter $exporter, string $destination): string
because of: https://github.com/oat-sa/extension-tao-outcomeui/pull/454/files#diff-79be62823084e93732cd5722ec913499fe58278a4f2faf9996eaff1305a38c7eR79

2022-12-29 15:25 UTC, bartlomiejmarszal approved these changes

2023-01-03 10:08 UTC, merged